In [7]:
from sklearn.datasets import load_diabetes
from sklearn.decomposition import PCA
import pandas as pd
import numpy as np

In [8]:
pca = PCA(n_components=2)
data = load_diabetes()

In [9]:
data = pd.DataFrame(data['data'],columns=data.feature_names)

In [10]:
data.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019908,-0.017646
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068330,-0.092204
2,0.085299,0.050680,0.044451,-0.005671,-0.045599,-0.034194,-0.032356,-0.002592,0.002864,-0.025930
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022692,-0.009362
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031991,-0.046641

In [13]:
x_pca = pca.fit_transform(data)

In [41]:
x_pca.shape

(442, 2)

In [46]:
data1 = pd.DataFrame(x_pca,columns={"hey","hy"})

In [47]:
data1

           hy       hey
0    0.027931 -0.092601
1   -0.134686  0.065263
2    0.012945 -0.077764
3    0.002345  0.018182
4   -0.035981  0.038621
5   -0.188660 -0.018125
6   -0.094835 -0.038316
7    0.098739  0.086945
8    0.028683 -0.041917
9   -0.010091 -0.023445
10  -0.183419 -0.072874
11   0.018880 -0.030087
12  -0.075932  0.046684
13   0.015147 -0.030969
14  -0.080169  0.086471
15   0.140488  0.045190
16   0.007586  0.043395
17   0.108839 -0.007068
18  -0.054995 -0.020373
19  -0.084265  0.044181
20  -0.095596 -0.013794
21  -0.091872 -0.039542
22  -0.079727  0.034232
23   0.179486 -0.083922
24  -0.061339 -0.011865
25   0.003924 -0.051083
26  -0.184829 -0.046787
27  -0.049697 -0.026312
28  -0.083679 -0.002874
29  -0.017189 -0.066990
..        ...       ...
412  0.085092  0.013571
413 -0.058847  0.054724
414  0.178445  0.075254
415  0.054368  0.031521
416  0.049081 -0.015002
417 -0.051296  0.009365
418  0.019231  0.160667
419 -0.136840 -0.020686
420  0.032405  0.011850
421  0.124745 -0.009652
422  0.083831  0.045028
423  0.104066 -0.002183
424  0.045617 -0.058687
425 -0.197220 -0.056061
426  0.136550  0.016945
427 -0.066937 -0.093880
428  0.179598 -0.041015
429 -0.051654  0.103379
430 -0.004452  0.050792
431 -0.040553 -0.037129
432  0.110531  0.049634
433 -0.091492  0.132093
434 -0.028901  0.041126
435 -0.056273  0.013957
436 -0.178999  0.055324
437  0.058958 -0.049275
438  0.060155  0.036211
439 -0.009763 -0.057337
440  0.032956  0.009994
441 -0.090561  0.189108

[442 rows x 2 columns]